hellotisiweb/Models/ErrorViewModel.cs
namespace hellotisiweb.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

hellotisiweb/Models/GuestbookModel.cs
namespace hellotisiweb.Models;

using mkcs.libtisiweb.ViewModels.Page;
using mkcs.libtisiweb.ViewModels.Content;

public record GuestbookModel : DefaultModel
{
    public int PageNumber { get; set;} = 0;

    public int PageCount { get; set;} = 0;

    public IList<GuestbookEntryViewModel> GuestbookEntries = new List<GuestbookEntryViewModel>();
}

hellotisiweb/Models/HomeIndexModel.cs
namespace hellotisiweb.Models;

public class HomeIndexModel
{
    public string? Title { get; set; }

    public string? Heading { get; set; }

    public string? Text { get; set; }

    public string? DebugInformation { get; set; }
}

hellotisiweb/Models/HomePrivacyModel.cs
namespace hellotisiweb.Models;

public record HomePrivacyModel(string? Title, string? Text);

hellotisiweb/Controllers/GuestbookController.cs
using Microsoft.AspNetCore.Mvc;
using mkcs.libtisiweb;
using mkcs.libtisiweb.Controllers;
using mkcs.libtisiweb.ViewModels.Content;
using mkcs.libtisiweb.Data.Access.Guestbook;
using hellotisiweb.Models;

namespace hellotisiweb.Controllers;

public class GuestbookController : TisiController
{
    private readonly ILogger<GuestbookController> _logger;
    private readonly ITisiwebAppService _tisiwebAppService;
    private readonly IGuestbookDataAccess _guestbookDataAccess;
    private readonly int _pageSize = 10;

    public GuestbookController(ILogger<GuestbookController> logger, ITisiwebAppService tisiwebAppService, IGuestbookDataAccess guestbookDataAccess)
        : base(tisiwebAppService, Constants.MainRepositoryId)
    {
        _logger = logger;
        _tisiwebAppService = tisiwebAppService ?? throw new ArgumentNullException(nameof(tisiwebAppService));
        _guestbookDataAccess = guestbookDataAccess ?? throw new ArgumentNullException(nameof(guestbookDataAccess));
        _logger.LogInformation(nameof(GuestbookController) + " ctor executed");
    }
    
    public IActionResult Index(int pageNumber = 1)
    {
        _logger.LogInformation($"{nameof(GuestbookController)}.{nameof(Index)}({pageNumber})");
        var model = HandleBasicFragments<GuestbookModel>(writeViewData: true);
        model.PageNumber = pageNumber;
        model.PageCount = _guestbookDataAccess.GetCount(Guid.Empty) / _pageSize;
        var entries = _guestbookDataAccess.GetEntries(Guid.Empty, (pageNumber - 1) * _pageSize, _pageSize);
        foreach (var entry in entries)
        {
            var vmEntry = new GuestbookEntryViewModel
            {
                ID = entry.ID.ToString(),
                Subject = entry.Subject,
                Text = entry.Text,
                Date = entry.Date,
                Author = entry.AuthorName
            };
            model.GuestbookEntries.Add(vmEntry);
        }
        return View(model);
    }
}

hellotisiweb/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using hellotisiweb.Models;
using mkcs.libtisiweb;
using mkcs.libtisiweb.Repositories;
using Microsoft.AspNetCore.Mvc.Filters;

namespace hellotisiweb.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly ITisiwebAppService _tisiwebAppService;
    private readonly IRepositoryManager _repositoryManager;
    private string _subset = string.Empty;

    public HomeController(ILogger<HomeController> logger, ITisiwebAppService tisiwebAppService)
    {
        _logger = logger;
        _tisiwebAppService = tisiwebAppService ?? throw new ArgumentNullException(nameof(tisiwebAppService));
        _repositoryManager = _tisiwebAppService.RepositoryManager;
    }

    public override void OnActionExecuting(ActionExecutingContext context)
    {
        if (string.IsNullOrEmpty(_subset))
        {
            _subset = _tisiwebAppService.GetURIParameter(context.RouteData.Values, "subset");
        }
    }

    public IActionResult Index()
    {
        HomeIndexModel homeIndexModel = new() {
            Heading = _repositoryManager.GetFragmentValueFromRepository("test", "heading", string.Empty),
            Title = _repositoryManager.GetFragmentValueFromRepository("test", "title", string.Empty),
            Text = _repositoryManager.GetFragmentValueFromRepository("test", "text", string.Empty),
            DebugInformation = string.Join("<br>", _repositoryManager.GetCategories())
        };
        return View(homeIndexModel);
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

hellotisiweb/Controllers/PicturesController.cs
using mkcs.libtisiweb;
using mkcs.libtisiweb.Repositories;
using mkcs.libtisiweb.Controllers;

namespace hellotisiweb.Controllers;

public class PicturesController : MediaController
{
    private readonly ILogger<PicturesController> _logger;
    private readonly ITisiwebAppService _tisiwebAppService;
    private readonly IMediaRepository _mediaRepository;

    protected override bool HandlesPictures => true;
    protected override string LocalFragmentRepositoryFile => "pictures.xml";
    protected override string LocalFragmentRepositoryNamespace => "Pictures.Details";
    protected override string MediaRootFolder => "~/pics";

    public PicturesController(ILogger<PicturesController> logger, ITisiwebAppService tisiwebAppService, IMediaRepository mediaRepository)
        : base(logger, tisiwebAppService, mediaRepository, Constants.MainRepositoryId)
    {
        _logger = logger;
        _tisiwebAppService = tisiwebAppService ?? throw new ArgumentNullException(nameof(tisiwebAppService));
        _mediaRepository = mediaRepository ?? throw new ArgumentNullException(nameof(mediaRepository));
        _logger.LogInformation(nameof(PicturesController) + " ctor executed");
    }
}

hellotisiweb/Controllers/PrivacyController.cs
using hellotisiweb.Models;
using Microsoft.AspNetCore.Mvc;
using mkcs.libtisiweb;
using mkcs.libtisiweb.Controllers;
using mkcs.libtisiweb.Repositories;

namespace hellotisiweb.Controllers;

public class PrivacyController : TisiController
{
    private readonly ILogger<PrivacyController> _logger;
    private readonly ITisiwebAppService _tisiwebAppService;
    private readonly IRepositoryManager _repositoryManager;

    public PrivacyController(ILogger<PrivacyController> logger, ITisiwebAppService tisiwebAppService)
        : base(tisiwebAppService, Constants.MainRepositoryId)
    {
        _logger = logger;
        _tisiwebAppService = tisiwebAppService ?? throw new ArgumentNullException(nameof(tisiwebAppService));
        _repositoryManager = _tisiwebAppService.RepositoryManager;
        _logger.LogInformation(nameof(PrivacyController) + " ctor executed");
    }

    private string GetFragmentValue(string fragmentName) => _repositoryManager.GetFragmentValueFromRepository(Constants.MainRepositoryId, "Privacy.Index." + fragmentName, Subset);

    public IActionResult Index()
    {
        HomePrivacyModel homePrivacyModel = new(
            GetFragmentValue("title"),
            GetFragmentValue("text")
        );
        return View(homePrivacyModel);
    }
}

hellotisiweb/Views/Guestbook/Index.cshtml
@model hellotisiweb.Models.GuestbookModel;

<div class="text-center">
    <h1 class="display-4">@Model.Title</h1>
    <h2>@Model.LongTitle</h2>

    <div class="fullwidth-table">
        <!-- Page navigation START -->
        @if (Model.PageNumber > 1)
        {
            <a class="btn btn-primary" asp-action="Index" asp-route-pageNumber="@(Model.PageNumber-1)">←</a>
        }
        else
        {
            <a class="btn btn-secondary" href="#">←</a>
        }
        @foreach (var pageNumber in Enumerable.Range(1, Model.PageCount))
        {
            <a class="btn @(pageNumber == Model.PageNumber ? "btn-success" : "btn-primary")" value="@pageNumber" asp-action="Index" asp-route-pageNumber="@pageNumber">@pageNumber</a>
        }
        @if (Model.PageNumber < Model.PageCount)
        {
            <a class="btn btn-primary" asp-action="Index" asp-route-pageNumber="@(Model.PageNumber+1)">→</a>
        }
        else
        {
            <a class="btn btn-secondary" href="#">→</a>
        }
        <!-- Page navigation END -->
        @foreach (var entry in Model.GuestbookEntries)
        {
            <div class="entry-header">
                <b>@entry.Subject</b> written by <b>@entry.Author</b> at <i>@entry.Date</i>
            </div>
            <div class="entry-body">
                @entry.Text
            </div>
        }
    </div>
</div>

hellotisiweb/Views/Home/Index.cshtml
@model HomeIndexModel
@{
    ViewData["Title"] = @Model.Title;
}

<div class="text-center">
    <h1 class="display-4">@Model.Heading</h1>
    <p>@Model.Text</p>
    <pre>@Model.DebugInformation</pre>
</div>

hellotisiweb/Views/Pictures/Index.cshtml
@model mkcs.libtisiweb.ViewModels.Page.Media.MediaIndexModel

    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
@foreach (var folderPart in Model.Folder.Split('/'))
{
    if (folderPart != Model.Folder.Split('/').Last())
    {
        <li class="breadcrumb-item"><a asp-area="" asp-controller="Pictures" asp-action="Index" asp-route-id="@Model.Folder.Substring(0, Model.Folder.IndexOf(folderPart + "/") + folderPart.Length)">@folderPart</a></li>
    }
    else
    {
        <li class="breadcrumb-item active" aria-current="page">@folderPart</li>
    }
}
      </ol>
    </nav>

<h1>@Model.Title</h1>
<p>@Model.LongTitle</p>

@if ((Model.MediaList?.Count ?? 0) == 0)
{
    <div>This folder does not contain any pictures!</div>
}
else
{
    @foreach (var picture in Model.MediaList ?? Enumerable.Empty<mkcs.libtisiweb.Models.MediaInfo>())
    {
        if (picture.ID == "lowres" || picture.ID == "midres")
        {
            continue;
        }
        <div class="gallery" style="text-align: center;">
        @if (picture.MediaType == mkcs.libtisiweb.Models.Enums.MediaType.Folder)
        {
            var folderRouteId = Model.Folder + "/" + picture.ID;
            <div style="font-size: xx-large;">📁</div>
            <a asp-area="" asp-controller="Pictures" asp-action="Index" asp-route-id="@folderRouteId">@picture.ID</a>
        }
        else
        {
                <a href="~/pics/@Model.Folder/@picture.ID">
                    <img src="~/pics/@Model.Folder/lowres/@picture.ID" alt="@picture.Description">
                </a>
                <div class="desc">@picture.Description<br>@picture.Created</div>
        }
        </div>
    }
}

hellotisiweb/Views/Privacy/Index.cshtml
@model HomePrivacyModel
@{
    ViewData["Title"] = @Model.Title;
}
<h1>@Model.Title</h1>

<p>@Model.Text</p>

hellotisiweb/Views/Shared/_Layout.cshtml
@using hellotisiweb.Helpers
@inherits LayoutPage<dynamic>
@inject TisiWebHtmlHelper<dynamic> Html

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - hellotisiweb</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/hellotisiweb.styles.css" asp-append-version="true" />
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
$(document).ready(function(){
  $('.dropdown-submenu a.nav-link').on("click", function(e){
    $(this).next('ul').toggle();
    e.stopPropagation();
    e.preventDefault();
  });
});
</script>
</head>
@{
    var _subset = ViewContext?.RouteData?.Values?["subset"]?.ToString() ?? string.Empty;
}
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">hellotisiweb @Html.Raw(Html.Foo(_subset))</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @Html.Raw(Html.CreateCodeForNavigationForSubset(_subset))
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023-2025 - @SiteName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>